// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMJZr8t4l3XVt-KN5CMdEgUct1CqukC_0',
    appId: '1:258782339328:web:858d389346d4252da8d3e5',
    messagingSenderId: '258782339328',
    projectId: 'wesal-6a246',
    authDomain: 'wesal-6a246.firebaseapp.com',
    storageBucket: 'wesal-6a246.firebasestorage.app',
    measurementId: 'G-10058DZCGM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuRJv0FPrA26v_3FUrF3xOBV1q8NDFacA',
    appId: '1:258782339328:android:d9fee14c39b177aba8d3e5',
    messagingSenderId: '258782339328',
    projectId: 'wesal-6a246',
    storageBucket: 'wesal-6a246.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDueHkvK38AKN441pVHMox-5Mi__7ZhwNo',
    appId: '1:258782339328:ios:386b7edb6b1959fca8d3e5',
    messagingSenderId: '258782339328',
    projectId: 'wesal-6a246',
    storageBucket: 'wesal-6a246.firebasestorage.app',
    iosBundleId: 'com.example.wesal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDueHkvK38AKN441pVHMox-5Mi__7ZhwNo',
    appId: '1:258782339328:ios:386b7edb6b1959fca8d3e5',
    messagingSenderId: '258782339328',
    projectId: 'wesal-6a246',
    storageBucket: 'wesal-6a246.firebasestorage.app',
    iosBundleId: 'com.example.wesal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMJZr8t4l3XVt-KN5CMdEgUct1CqukC_0',
    appId: '1:258782339328:web:40ad174ac74a6517a8d3e5',
    messagingSenderId: '258782339328',
    projectId: 'wesal-6a246',
    authDomain: 'wesal-6a246.firebaseapp.com',
    storageBucket: 'wesal-6a246.firebasestorage.app',
    measurementId: 'G-07Q79SV20Q',
  );
}
